import { useState } from 'react';

export default function TeamForm({ initialData = {}, onSubmit}) {
    const [name, setName] = useState('');

    const handleSubmit = (e) => {
        e.preventDefault();
        onSubmit({name}); //and all the other data things
    }
    return (
        <form onSubmit={handleSubmit}>
            <label>Team Number</label> {/* Hmmmmm. I've had this just an autogenerated key. Talk to office */}
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} />
            <button type="submit">Submit</button> {/* we could have this be different for create and update (submit/save) would need to add param to func */}
        </form>
    );
}