CREATE DATABASE IF NOT EXISTS capstone;

-- CREATE DATABASE test; -- maybe we want this for something?


-- EVENTUALLY PASTE (OR LINK) IN ALL THE OTHER CREATE TABLE CODES OR MAYBE A BACKUP OF THE DATABASE
